### ISSUE TITLE
integer underflow - intentional?

### ISSUE THREAD

**Issue by jefftrull** [lemire/Code-used-on-Daniel-Lemire-s-blog#18]
Hi! While experimenting with your code I ran across something:

https://github.com/lemire/Code-used-on-Daniel-Lemire-s-blog/blob/e96243e0143d6275ec0883e6e7150662c9dd4b6e/2018/07/05/dotproduct.c#L186

Because "i" is unsigned, 10-i is a very large number for i > 10. Feel free to close if that's intended :)

**Comment by lemire** [comment]
Can you elaborate? 

As you may suspect, I just wrote this code without thinking too hard.

**Comment by jefftrull** [comment]
If you print out the values assigned to the x1 and x2 arrays, the first ten entries have some similarity in that the x1 values are small (<1) and increasing while the x2 values are small and decreasing. As soon as you reach i=11 the x2 values become large and positive (above 10^16 IIRC). This is because (i-10) is an unsigned value. I wasn't sure if that was the intention or not, so I thought I'd ask.

If you substitute `(10 - (int)i)` instead, the x2 values smoothly decrease through 0 and into small negative numbers.

**Comment by lemire** [comment]
Do you expect that this matters... i.e. does it impact the timings?

**Comment by jefftrull** [comment]
Ah, honestly I don't know. It seemed strange, that's all. I thought maybe it was causing some overflow issue or something - at first I didn't understand why each algorithm got a different result, so that's what led me that way. If it's supposed to work like that, no problem!

**Comment by lemire** [comment]
Well, it might be an issue... floating point numbers are strange... But I don’t see it at a glance.

The functions don’t compute the same thing... so they won’t output the same values.

**Comment by jefftrull** [comment]
OK good deal, thanks!
