### ISSUE TITLE
AVX-512 light and heavy operations reversed

### ISSUE THREAD

**Issue by travisdowns** [lemire/Code-used-on-Daniel-Lemire-s-blog#19]
In mandelbrot.c we have the following code:

```
#ifdef USEHEAVYAVX512
    b = _mm512_add_epi32(b, t);
#else 
    b = _mm512_mul_epi32(b, t);
#endif 
```

Unless I am mistaken, these lines of code should be reversed: the `mul` should be the heavy operation and the `add` should be the light operation.

**Comment by lemire** [comment]
I am going to fix this.

**Comment by lemire** [comment]
Fixed with the last commit. Thanks.
