### ISSUE TITLE
mandelbrot.c is optimized away

### ISSUE THREAD

**Issue by travisdowns** [lemire/Code-used-on-Daniel-Lemire-s-blog#22]
I was trying to run your mandelbrot.c benchmark to see what's up with AVX throttling, but when I profile it, it is spending all its time simply incrementing a single number until passes some threshold. 

Basically it looks like it is just executing the line `for (y = 0; y < h; ++y)` and the entire body of the loop including the nested loop has been optimized away, which occurs at either `-O2` or `-O3` (but not `-O1`).

 This occurs because none of the values calculated in the loop are used because the `putc(byte_acc,stdout);` lines which were outputting the fractal values are commented out. 

If I add the lines:

```
printf("Zr=%5.2f, Zi=%5.2f, Cr=%5.2f, Ci=%5.2f, Tr=%5.2f, Ti=%5.2f\n", Zr, Zi, Cr, Ci, Tr, Ti);
printf("byte_acc = %d, bit_num = %d\n", byte_acc, bit_num);
```

Runtime with the default `w` and `h` (32,000) jumps to ~100 seconds from about 1 second, and the profile shows the code doing more work. Even that doesn't seem totally safe since the inner loop is mostly starting from scratch each time so it's possible the outer iterations could be eliminated. To keep it as similar to the original test, I recommend adding a `long byte_total = 0;` at the top of main, and `byte_total += byte_acc;` at the two locations that `// putc(byte_acc,stdout);` appeared, and then a `printf("byte_total = %ld", byte_total);` right before `return 0`.

**Comment by lemire** [comment]
Thanks for reporting the problem.

**Comment by travisdowns** [comment]
I added one comment on the commit.

**Comment by lemire** [comment]
Yes. But I don't think it is a problem when running my scripts. They do not depend on the returned value.

**Comment by travisdowns** [comment]
I didn't say it was a problem with your scripts in particular (they continue on failure), but I often use pipelines with `&&` and I put `set -e` in my scripts so they fail if a command fails. Just an FYI that benchmarks written this way are annoying to use (particularly since they may fail sporadically since the value is chopped down to 8 bits on Unix-likes at least).

**Comment by lemire** [comment]
I am re-running today's results and they do not appear to be affected by this change.

**Comment by lemire** [comment]
> No, I didn't see any effect in the relative performance between the 3 variants from this change, (...)

I presume you did not test with the Xeon Gold. That's what I am doing now.

> BTW, did you change this W-2104 box to not use intel_pstate? I noticed it using acpi_cpufreq. Usually you get better performance from intel_pstate and it is the default, but I see acpi_cpufreq governor being used.

I made no such change. I don't know what acpi_cpufreq is.

**Comment by travisdowns** [comment]
> I made no such change. I don't know what acpi_cpufreq is.

`acpi_cpufreq` and `intel_pstate` are "CPU governors" available for Linux. Basically they control the CPU speed of the various cores to save power and whatever. `intel_pstate` is the newer one written by Intel for Intel chips: the main difference is that it enables HWP ("hardware power management") which means it leaves it up to the chip to do all frequency changes. `acpi_cpufreq` does changes below the turbo threshold(s) in the OS. 

Normally Ubuntu `16.04` should default to `intel_pstate` for Intel boxes but maybe Skylake-X is "too new" and "16.04" too old, or there is some other reason it wasn't selected. I'm using Skylake client and it used `intel_pstate` by default.

It probably doesn't make any difference, but it might be something to check one day.

**Comment by travisdowns** [comment]
> I presume you did not test with the Xeon Gold. That's what I am doing now.

Correct, I've only tried the W-2104 so far.

**Comment by lemire** [comment]
I know what performance governors are, but I don't know what `acpi_cpufreq` is. I did not know about `intel_pstate`.

Did I give you root access to that machine?

**Comment by lemire** [comment]
Anyhow, I am going to be refreshing all the numbers on my blog now... boring work. 

Still, I thank you.

**Comment by travisdowns** [comment]
> I know what performance governors are, but I don't know what acpi_cpufreq is. I did not know about intel_pstate.
> 
> Did I give you root access to that machine?

Actually I used the wrong term, they are not governors. They are scaling _drivers_. `intel_pstate` and `acpi_cpufreq` are two possible drivers that control your CPU scaling. Only one drive can be active and is is selected at boot and cannot be changed. Each driver offers one or more _governors_ which is the thing you are familiar with like `performance`, `powersaving`, etc. They don't all offer the same governors, and even governors with the same name don't necessarily do the same thing. It happens that both `cpufreq` and `intel_pstate` offer `performance` and `powersaving` but Intel's `powersaving` is very different! 

Yup I have root.

It seems Skylake-X is just too new for `intel_pstate` on the old kernel on that box. See [here](https://www.phoronix.com/scan.php?page=news_item&px=Skylake-X-P-State-Linux-4.16) for example.  BTW I woudl recommend enabling the Ubuntu HWE stack on boxes if you want to use newer kernels. It's a second line of supported kernels which are kept more up to date versus the default which usually doesn't change.
