### ISSUE TITLE
Infinite loop in scalar despacing code after NEON section?

### ISSUE THREAD

**Issue by neocpp89** [lemire/Code-used-on-Daniel-Lemire-s-blog#41]
https://github.com/lemire/Code-used-on-Daniel-Lemire-s-blog/blob/87537d11b09437a9a1a279b1949bdbd83bb05ffe/2017/07/10/despacer.h#L114-L120

Unless I misunderstand something, doesn't `i` need to be incremented to break out of this? The fully scalar version at the top of the file looks correct with `i++`, but none of the NEON versions do.

**Comment by lemire** [comment]
Thank. You are correct. I think I fixed it.
