### ISSUE TITLE
Boost Software License?

### ISSUE THREAD

**Issue by vinniefalco** [lemire/Code-used-on-Daniel-Lemire-s-blog#42]
Apache isn't quite as permissive as the Boost Software License, would you consider re-licensing or dual-licensing this code under the Boost Software License? https://www.boost.org/users/license.html

**Comment by lemire** [comment]
You will have to be more specific. The code in this repo is licensed as follows...

> Unless otherwise stated, I make no copyright claim on this code: you may consider it to be in the public domain.

This is the code that accompanies my blog. This is just research-oriented code... none of it is meant to be reused as is.

There may be exceptions... if there is code you'd like to reuse here and where the licensing is a problem, please let me know.

**Comment by vinniefalco** [comment]
I was certain I saw an Apache license in there, but now that I look again I don't see it! I was looking at this article

https://lemire.me/blog/2016/06/27/a-fast-alternative-to-the-modulo-reduction/

Ah, I think I found the code:

https://github.com/lemire/fastvalidate-utf-8

**Comment by lemire** [comment]
Right. If there is a concern with the license of this other repo., please either open an issue over there, or submit a PR.

If one wants to use this code in a Boost-related project, it would certainly be the intention that it is possible. I don't know the difference between the Boost and the Apache license. If there is some incompatibility, I am sure we can resolve it.
