### ISSUE TITLE
comments on the multibinarysearch.cpp (2019/09/14)

### ISSUE THREAD

**Issue by insoulity** [lemire/Code-used-on-Daniel-Lemire-s-blog#46]
Thanks for the wonderful articles as always.

I'd like to drop a few comments on the repo below and also ask a few questions as well.
https://github.com/lemire/Code-used-on-Daniel-Lemire-s-blog/tree/master/2019/09/14

1. It seems branchless4 (https://github.com/lemire/Code-used-on-Daniel-Lemire-s-blog/blob/master/2019/09/14/multiplebinarysearch.cpp#L200) and branchless4_lfence (https://github.com/lemire/Code-used-on-Daniel-Lemire-s-blog/blob/master/2019/09/14/multiplebinarysearch.cpp#L224) to be misnamed each other.

2. Your branch_search (https://github.com/lemire/Code-used-on-Daniel-Lemire-s-blog/blob/master/2019/09/14/multiplebinarysearch.cpp#L27) and branchfree_search (https://github.com/lemire/Code-used-on-Daniel-Lemire-s-blog/blob/master/2019/09/14/multiplebinarysearch.cpp#L51) are different in the sense the formal allows an early exit with the equality test while the latter doesn't. It may or may not impact on the performance, depending on your machine and key array size.

I'd like to understand the purpose of cacheline_access added between experiments. Could you also tell me what you'd intend there?
(Very minor though, before and after branchless_lfence (https://github.com/lemire/Code-used-on-Daniel-Lemire-s-blog/blob/master/2019/09/14/multiplebinarysearch.cpp#L1245), there are 1 cache_lline access and 3 while all the rest are two and two.

Thanks,
Yongkee

**Comment by lemire** [comment]
Thank you for the comments. The cache line access is to try to ensure that the data is held in cache.
