### ISSUE TITLE
aggressive compiler defense

### ISSUE THREAD

**Issue by paulmcq** [lemire/Code-used-on-Daniel-Lemire-s-blog#51]
Suggest adding 'return bogus;' at end of main() to defend against an extremely aggressive compiler optimizer. IIUC, a compiler would be allowed to completely eliminate the computation of 'bogus'.
AFAIK this is only a theoretical problem. On GCC -O3 version 7.5 the code appears to be compiled as intended.
Edit, forgot to specify:
https://github.com/lemire/Code-used-on-Daniel-Lemire-s-blog/blob/master/2013/12/26/gcd.cpp

**Comment by lemire** [comment]
Can you issue a PR? There is 10 years of code in this repository (literally)  and many things called "bogus".

**Comment by paulmcq** [comment]
Oops. My bad.
Here is the one I am addressing:
https://github.com/lemire/Code-used-on-Daniel-Lemire-s-blog/blob/master/2013/12/26/gcd.cpp

I am new to GIT, so here is a patch. When I learn how to do a sensible PR,
I will let you know. And this is a very low priority because the GCC code
works as intended (ver 7.5.0).
    bogus += test(1000*1000*1000);   // line 443
    return bogus;                                  // proposed insertion
}                                                          // line 444

**Comment by lemire** [comment]
Thanks. Closing after latest commit.

**Comment by paulmcq** [comment]
Thanks. I actually like your change better than my proposal.
Yours will fail LOUDLY if the compiler messes up.
