### ISSUE TITLE
Wrong number of number of generators reported

### ISSUE THREAD

**Issue by azelcer** [lemire/Code-used-on-Daniel-Lemire-s-blog#52]
This line corresponds to two generators, but three is reported

https://github.com/lemire/Code-used-on-Daniel-Lemire-s-blog/blob/041d5e9e07ee14281934d6b8a26985d99837b0c8/2019/03/19/fastestrng.cpp#L64

**Comment by lemire** [comment]
That's correct. There is a typo.

**Comment by azelcer** [comment]
Or maybe a copy-pasto ;-)

**Comment by lemire** [comment]
Fixed by a commit.
