### ISSUE TITLE
kpc_get_thread_counters crash

### ISSUE THREAD

**Issue by michaeleisel** [lemire/Code-used-on-Daniel-Lemire-s-blog#56]
When I try to run `get_counters` from the `2021/03/24` project, I get a crash when trying to run `kpc_get_thread_counters` even as sudo. I'm on an Intel Mac, and I know the article is for M1, so maybe that's the issue? Just figured I'd check.

**Comment by lemire** [comment]
Yes. I do not expect it to work on anything but M1.

It could be fixed, of course, but I did not do the work.

**Comment by lemire** [comment]
I am closing this issue. I am not planning on working on x64 macos. Pull requests invited.
