### ISSUE TITLE
Please add license

### ISSUE THREAD

**Issue by dov** [lemire/Code-used-on-Daniel-Lemire-s-blog#58]
There is no license attached to the code, which means it defaults to being "all rights reserved". It would be a nice courtesy to the community if you would make your intention about the license explicit. (With hope that you will release it under a permissive license. :-) )

**Comment by lemire** [comment]
Thanks for your comment.

Licensing is specifically addressed in the README:

https://github.com/lemire/Code-used-on-Daniel-Lemire-s-blog#licensing

Note that you should not use the code in this repo in production. This code is not meant to be reused as-is. It will have bugs.

**Comment by dov** [comment]
Thanks! I was especially interested in "iterating over set bits quickly" in order to create a fast iterative run-length encoding.

**Comment by lemire** [comment]
@dov You should feel free to copy and paste the code, and then adapt it. It is often useful if you can link to the original blog post (for credit). I think I am clear enough: this code is in the public domain unless there is a specific mention to the contrary.
