### ISSUE TITLE
Regarding Interleaving 2 bits - 2 bits

### ISSUE THREAD

**Issue by Darshvino** [lemire/Code-used-on-Daniel-Lemire-s-blog#61]
Hi @lemire,

Thanks for all your contributions! It will definitely help many with their work. And great references for learning.

I was referring to your blog on interleaving bits with the SIMD approach https://lemire.me/blog/2018/01/09/how-fast-can-you-bit-interleave-32-bit-integers-simd-edition/. I wanted to apply the same technique for interleaving  2 bits - 2 bits. 

Below is what I want to do: 

```
A(256 bit reg) = 110010.....( 128(2bit) values)
B(256 bit reg) = 011101.....( 128(2bit) values)

C(256 bit reg) = 110100111001......(merged, lower 128 bits)
D(256-bit reg) = ....................................(merged, higher 128 bits)

```

How can we apply the same technique for the above??

It would be a great help if you can assist me in interleaving 2bits-2bits efficiently.

Thanks,
Darshan C G

**Comment by lemire** [comment]
Thanks for the good words.

If you skip the last step, it should do... so instead of
```C++
__m256i interleave_uint8_with_zeros_avx(__m256i word) {
  const __m256i m3 = _mm256_set1_epi64x(0x0f0f0f0f0f0f0f0f);
  const __m256i m4 = _mm256_set1_epi64x(0x3333333333333333);
  const __m256i m5 = _mm256_set1_epi64x(0x5555555555555555);
  word = _mm256_xor_si256(word, _mm256_slli_epi16(word, 4));
  word = _mm256_and_si256(word, m3);
  word = _mm256_xor_si256(word, _mm256_slli_epi16(word, 2));
  word = _mm256_and_si256(word, m4);
  word = _mm256_xor_si256(word, _mm256_slli_epi16(word, 1));
  word = _mm256_and_si256(word, m5);
  return word;
}
```

Just do...

```C++
__m256i interleave_uint8_with_zeros_avx(__m256i word) {
  const __m256i m3 = _mm256_set1_epi64x(0x0f0f0f0f0f0f0f0f);
  const __m256i m4 = _mm256_set1_epi64x(0x3333333333333333);
  word = _mm256_xor_si256(word, _mm256_slli_epi16(word, 4));
  word = _mm256_and_si256(word, m3);
  word = _mm256_xor_si256(word, _mm256_slli_epi16(word, 2));
  word = _mm256_and_si256(word, m4);
  return word;
}
```

There might be further possible optimizations.

**Comment by Darshvino** [comment]
Hi @lemire,

Thank you for your kind reply.

Can we do the same using the LUT approach?

**Comment by lemire** [comment]
Yes although the benefits will be less significant.

**Comment by Darshvino** [comment]
Ohh I See got it! Thank you for your response @lemire
